package com.amsavarthan.game.trivia.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFFb02d2c)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdad5)
val md_theme_light_onPrimaryContainer = Color(0xFF410003)
val md_theme_light_secondary = Color(0xFF9c4145)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffd9da)
val md_theme_light_onSecondaryContainer = Color(0xFF400008)
val md_theme_light_tertiary = Color(0xFF9c4141)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdad7)
val md_theme_light_onTertiaryContainer = Color(0xFF400005)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a19)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a19)
val md_theme_light_surfaceVariant = Color(0xFFf4dddb)
val md_theme_light_onSurfaceVariant = Color(0xFF534341)
val md_theme_light_outline = Color(0xFF857371)
val md_theme_light_inverseOnSurface = Color(0xFFfbeeec)
val md_theme_light_inverseSurface = Color(0xFF362f2e)

val md_theme_dark_primary = Color(0xFFffb3ab)
val md_theme_dark_onPrimary = Color(0xFF680007)
val md_theme_dark_primaryContainer = Color(0xFF8d1217)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdad5)
val md_theme_dark_secondary = Color(0xFFffb2b4)
val md_theme_dark_onSecondary = Color(0xFF5f131b)
val md_theme_dark_secondaryContainer = Color(0xFF7e2a30)
val md_theme_dark_onSecondaryContainer = Color(0xFFffd9da)
val md_theme_dark_tertiary = Color(0xFFffb3b0)
val md_theme_dark_onTertiary = Color(0xFF5f1317)
val md_theme_dark_tertiaryContainer = Color(0xFF7d2a2b)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdad7)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a19)
val md_theme_dark_onBackground = Color(0xFFede0de)
val md_theme_dark_surface = Color(0xFF201a19)
val md_theme_dark_onSurface = Color(0xFFede0de)
val md_theme_dark_surfaceVariant = Color(0xFF534341)
val md_theme_dark_onSurfaceVariant = Color(0xFFd7c1bf)
val md_theme_dark_outline = Color(0xFFa08c8a)
val md_theme_dark_inverseOnSurface = Color(0xFF201a19)
val md_theme_dark_inverseSurface = Color(0xFFede0de)

val seed = Color(0xFFa62626)
val error = Color(0xFFba1b1b)